### ISSUE TITLE
编译liquid合约时遇到colored版本问题

### ISSUE THREAD

**Issue by Yawn1ng** [WeBankBlockchain/cargo-liquid#28]
执行`cargo liquid build`编译liquid合约时出现错误
```
error: package `colored v2.1.0` cannot be built because it requires rustc 1.70 or newer, while the currently active rustc version is 1.68.0-nightly
Either upgrade to rustc 1.70 or newer, or use
cargo update -p colored@2.1.0 --precise ver
where `ver` is the latest version of `colored` supporting rustc 1.68.0-nightly
ERROR: xbuild failed with status exit status: 101
```
运行以下命令，该错误仍然存在
```shell
cargo update -p colored@2.1.0 --precise 2.0.0
```
升级rustc到1.70或以上，wasm又会出现问题

**Comment by Yawn1ng** [comment]
已解决

**Comment by 2473o** [comment]
> 已解决

问下是怎么解决wasm的，我出现的是这个问题
[https://github.com/WeBankBlockchain/liquid/issues/42](url)

**Comment by Yawn1ng** [comment]
我用的是官方文档中的1.68.0-nightly。我这个issue的解决方案为指定colored版本为2.0.0

**Comment by miao1108** [comment]
请问一下您怎么指定colored版本为2.0.0哇，我怎么指定都是2.1.0

**Comment by 2473o** [comment]
> 请问一下您怎么指定colored版本为2.0.0哇，我怎么指定都是2.1.0

crate仓库的依赖改了，导致的版本问题，只能降/升版本

**Comment by miao1108** [comment]
我已经在cargo.toml中指定colored = "2.0.0"，也输入命令cargo update -p colored@2.1.0 --precise 2.0.0，而且使用cargo tree查看依赖全部都是2.0.0，但是一旦编译不知道谁又会重新下载2.0.1，然后报错error: package `colored v2.1.0` cannot be built because it requires rustc 1.70 or newer, while the currently active rustc version is 1.68.0-nightly
Either upgrade to rustc 1.70 or newer，请问你们都是啥方法降低版本的哇

**Comment by Joe-139** [comment]
我fork了官方仓库，改了colored的版本，然后修改自己项目的`cargo.toml`文件的dependencies，调用修改后的liquid
```
liquid_lang = { git = "https://github.com/Yawn1ng/liquid", rev = "8783fbe7dd1645b73640114891fc7ff3934e83ec", package = "liquid_lang", default-features = false, features = ["contract"] }
liquid_primitives = { git = "https://github.com/Yawn1ng/liquid", rev = "8783fbe7dd1645b73640114891fc7ff3934e83ec", package = "liquid_primitives", default-features = false }
liquid_prelude = { git = "https://github.com/Yawn1ng/liquid", rev = "8783fbe7dd1645b73640114891fc7ff3934e83ec", package = "liquid_prelude", default-features = false }
liquid_macro = { git = "https://github.com/Yawn1ng/liquid", rev = "8783fbe7dd1645b73640114891fc7ff3934e83ec", package = "liquid_macro", default-features = false }
liquid_abi_gen = { git = "https://github.com/Yawn1ng/liquid", rev = "8783fbe7dd1645b73640114891fc7ff3934e83ec", package = "liquid_abi_gen", default-features = false, optional = true }
```
还有`.liquid/abi_gen/Cargo.toml`也要做相应修改

**Comment by Yawn1ng** [comment]
同时我也fork了cargo-liquid，修改了template文件，在官方仓库未更新前可以装这个版本的cargo-liquid曲线救国，后续new新项目的时候就不需要修改项目toml文件了

**Comment by 2473o** [comment]
> 同时我也fork了cargo-liquid，修改了template文件，在官方仓库未更新前可以装这个版本的cargo-liquid曲线救国，后续new新项目的时候就不需要修改项目toml文件了

目前有个依赖home@0.5.9出现问题，该依赖需要的版本是`1.70.0`，切换编译后没问题
换回`1.68.0-nightly`后`cargo test`  hello_world [出现同样的源码问题](https://github.com/WeBankBlockchain/liquid/issues/42)
注释后可用，没有用过宏 :(
```
error: proc macro panicked
   --> /home/alex/.cargo/git/checkouts/liquid-beeaab2b7fe42dde/8783fbe/primitives/src/types/fixed_size_bytes.rs:218:1
    |
218 | / seq!(N in 1..=32 {
219 | |     impl_bytes_from_bytes!(
220 | |         #(Bytes#N as Bytes{+1#N => 32},)*
221 | |     );
222 | | });
    | |__^
    |
    = help: message: called `Option::unwrap()` on a `None` value
````
且`cargi liquid build`成功，能够在WeBankFront中部署但无法调用
![image](https://github.com/WeBankBlockchain/cargo-liquid/assets/86139845/d5980e30-d331-49e4-9c47-79ca35377f06)
```
2024-03-29 08:20:14.784 [http-nio-5002-exec-6] INFO  ContractController() - ifChanged start. groupId:group0 contractId:23
2024-03-29 08:20:14.841 [http-nio-5002-exec-3] INFO  KeyStoreController() - start getLocalKeyStoreList.
2024-03-29 08:20:16.284 [http-nio-5002-exec-4] INFO  TransController() - transHandleLocal start. ReqTransHandle:[{"user":"0xbfd6a200030d469400a0e483d46da43105b5c403","contractName":"hello_world","version":"","contractAddress":"/test/hello_world_0","contractPath":"hello_world","funcName":"get","groupId":"group0","contractAbi":[{"constant":true,"inputs":[],"name":"get","outputs":[{"internalType":"string","type":"string"}],"type":"function","funcId":1}],"funcParam":[],"useAes":false,"useCns":false,"cnsName":"","isWasm":true}]
2024-03-29 08:20:16.284 [http-nio-5002-exec-4] INFO  TransController() - transHandleLocal start startTime:1711700416284
2024-03-29 08:20:16.938 [http-nio-5002-exec-4] ERROR ExceptionsHandler() - catch  exception: []
java.lang.NullPointerException: null
        at com.webank.webase.front.transaction.TransService.getABIDefinition(TransService.java:589) ~[WeBASE-Front-3.1.1.jar:?]
        at com.webank.webase.front.transaction.TransService.transHandleLocal(TransService.java:254) ~[WeBASE-Front-3.1.1.jar:?]
        at com.webank.webase.front.transaction.TransController.transHandleLocal(TransController.java:130) ~[WeBASE-Front-3.1.1.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-5.3.30.jar:5.3.30]
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150) ~[spring-web-5.3.30.jar:5.3.30]
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117) ~[spring-webmvc-5.3.30.jar:5.3.30]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) ~[spring-webmvc-5.3.30.jar:5.3.30]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808) ~[spring-webmvc-5.3.30.jar:5.3.30]
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.3.30.jar:5.3.30]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1072) ~[spring-webmvc-5.3.30.jar:5.3.30]
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:965) ~[spring-webmvc-5.3.30.jar:5.3.30]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.3.30.jar:5.3.30]
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909) ~[spring-webmvc-5.3.30.jar:5.3.30]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:555) ~[tomcat-embed-core-9.0.82.jar:4.0.FR]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.3.30.jar:5.3.30]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:623) ~[tomcat-embed-core-9.0.82.jar:4.0.FR]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209) ~[tomcat-embed-core-9.0.82.jar:9.0.82]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[tomcat-embed-core-9.0.82.jar:9.0.82]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51) ~[tomcat-embed-websocket-9.0.82.jar:9.0.82]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[tomcat-embed-core-9.0.82.jar:9.0.82]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[tomcat-embed-core-9.0.82.jar:9.0.82]
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.3.30.jar:5.3.30]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.30.jar:5.3.30]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[tomcat-embed-core-9.0.82.jar:9.0.82]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[tomcat-embed-core-9.0.82.jar:9.0.82]
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.3.30.jar:5.3.30]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.30.jar:5.3.30]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[tomcat-embed-core-9.0.82.jar:9.0.82]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[tomcat-embed-core-9.0.82.jar:9.0.82]
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.3.30.jar:5.3.30]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.30.jar:5.3.30]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[tomcat-embed-core-9.0.82.jar:9.0.82]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[tomcat-embed-core-9.0.82.jar:9.0.82]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:168) ~[tomcat-embed-core-9.0.82.jar:9.0.82]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90) ~[tomcat-embed-core-9.0.82.jar:9.0.82]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:481) ~[tomcat-embed-core-9.0.82.jar:9.0.82]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130) ~[tomcat-embed-core-9.0.82.jar:9.0.82]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93) ~[tomcat-embed-core-9.0.82.jar:9.0.82]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) ~[tomcat-embed-core-9.0.82.jar:9.0.82]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) ~[tomcat-embed-core-9.0.82.jar:9.0.82]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390) ~[tomcat-embed-core-9.0.82.jar:9.0.82]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63) ~[tomcat-embed-core-9.0.82.jar:9.0.82]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:928) ~[tomcat-embed-core-9.0.82.jar:9.0.82]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1794) ~[tomcat-embed-core-9.0.82.jar:9.0.82]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) ~[tomcat-embed-core-9.0.82.jar:9.0.82]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-embed-core-9.0.82.jar:9.0.82]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-9.0.82.jar:9.0.82]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.82.jar:9.0.82]
        at java.lang.Thread.run(Thread.java:829) ~[?:?]
2024-03-29 08:20:16.938 [http-nio-5002-exec-4] WARN  ExceptionsHandler() - bindExceptionHandler return:{"code":500,"errorMessage":null}
```
